kind: ActiveMQArtemis
apiVersion: broker.amq.io/v1beta1
metadata:
  application: broker-amq-app
  name: broker-amq
spec:
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 1
  acceptors:
  - name: mqtt
    protocols: mqtt
    port: 1883
